## Regression model with Keras


<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

<strong>1. Cement</strong>

<strong>2. Blast Furnace Slag</strong>

<strong>3. Fly Ash</strong>

<strong>4. Water</strong>

<strong>5. Superplasticizer</strong>

<strong>6. Coarse Aggregate</strong>

<strong>7. Fine Aggregate</strong>


## Download and Clean Dataset

Let's start by importing the <em>pandas</em> and the Numpy libraries.

In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [45]:
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [46]:
concrete_data.shape

(1030, 9)

In [47]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [48]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [55]:
y = concrete_data
X = concrete_data

target=concrete_data['Strength']




X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3)
print("\nX_train:\n")
print(X_train.head())
print(X_train.shape)

print("\nX_test:\n")
print(X_test.head())
print(X_test.shape)

0       79.99
1       61.89
2       40.27
3       41.05
4       44.30
        ...
1025    44.28
1026    31.18
1027    23.70
1028    32.77
1029    32.40
Name: Strength, Length: 1030, dtype: float64

X_train:

     Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
252   250.0                 0.0     95.7  187.4               5.5
508   424.0                22.0    132.0  178.0               8.5
323   249.1                 0.0     98.8  158.1              12.8
772   382.0                 0.0      0.0  186.0               0.0
203   190.7                 0.0    125.4  162.1               7.8

     Coarse Aggregate  Fine Aggregate  Age  Strength
252             956.9           861.2   56     38.33
508             882.0           750.0    3     32.01
323             987.8           889.0  100     51.06
772            1047.0           739.0    7     24.00
203            1090.0           804.0  100     40.57
(721, 9)

X_test:

      Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
1001   297.8               137.2    106.9  201.3               6.0
499    491.0                26.0    123.0  210.0               3.9
825    397.0                 0.0      0.0  185.0               0.0
369    218.9                 0.0    124.1  158.5              11.3
5      266.0               114.0      0.0  228.0               0.0

      Coarse Aggregate  Fine Aggregate  Age  Strength
1001             878.4           655.3   28     53.52
499              882.0           699.0   28     55.55
825             1040.0           734.0   28     39.09
369             1078.7           794.9    3     15.34
5                932.0           670.0   90     47.03
(309, 9)

## Build a Neural Network

In [56]:
import keras
from keras.models import Sequential
from keras.layers import Dense


n_cols = concrete_data.shape[1] # number of predictors

In [57]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [58]:
model = regression_model()
model.fit(concrete_data, target, validation_split=0.3, epochs=50, verbose=2)

WARNING:tensorflow:From /home/arnab/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 1s - loss: 37613.3496 - val_loss: 20323.6697
Epoch 2/50
 - 0s - loss: 11420.8305 - val_loss: 4812.4606
Epoch 3/50
 - 0s - loss: 2556.7015 - val_loss: 1275.5026
Epoch 4/50
 - 0s - loss: 1216.5434 - val_loss: 952.5119
Epoch 5/50
 - 0s - loss: 1108.8714 - val_loss: 921.8672
Epoch 6/50
 - 0s - loss: 1055.8098 - val_loss: 896.5686
Epoch 7/50
 - 0s - loss: 1009.7572 - val_loss: 862.3760
Epoch 8/50
 - 0s - loss: 963.3037 - val_loss: 836.2746
Epoch 9/50
 - 0s - loss: 917.7314 - val_loss: 805.2596
Epoch 10/50
 - 0s - loss: 873.5863 - val_loss: 773.1572
Epoch 11/50
 - 0s - loss: 831.9910 - val_loss: 744.3375
Epoch 12/50
 - 0s - loss: 788.3646 - val_loss: 714.3696
Epoch 13/50
 - 0s - loss: 746.9806 - val_loss: 686.2612
Epoch 14/50
 - 0s - loss: 707.8693 - val_loss: 656.2068
Epoch 15/50
 - 0s - loss: 671.2614 - val_loss: 628.3956
Epoch 16/50
 - 0s - loss: 634.6197 - val_loss: 606.7942
Epoch 17/50
 - 0s - loss: 598.2811 - val_loss: 575.3873
Epoch 18/50
 - 0s - loss: 566.5205 - val_loss: 549.1873
Epoch 19/50
 - 0s - loss: 535.1254 - val_loss: 524.4007
Epoch 20/50
 - 0s - loss: 503.7758 - val_loss: 499.4249
Epoch 21/50
 - 0s - loss: 474.3373 - val_loss: 479.5082
Epoch 22/50
 - 0s - loss: 449.0726 - val_loss: 453.1606
Epoch 23/50
 - 0s - loss: 422.7070 - val_loss: 430.7647
Epoch 24/50
 - 0s - loss: 397.8578 - val_loss: 410.4851
Epoch 25/50
 - 0s - loss: 374.8532 - val_loss: 390.1207
Epoch 26/50
 - 0s - loss: 352.9971 - val_loss: 368.5343
Epoch 27/50
 - 0s - loss: 332.0965 - val_loss: 348.7371
Epoch 28/50
 - 0s - loss: 313.0843 - val_loss: 328.5386
Epoch 29/50
 - 0s - loss: 294.5330 - val_loss: 312.3025
Epoch 30/50
 - 0s - loss: 278.8940 - val_loss: 293.8315
Epoch 31/50
 - 0s - loss: 261.6533 - val_loss: 274.9844
Epoch 32/50
 - 0s - loss: 245.1787 - val_loss: 260.4956
Epoch 33/50
 - 0s - loss: 231.3449 - val_loss: 243.9859
Epoch 34/50
 - 0s - loss: 217.5148 - val_loss: 228.1021
Epoch 35/50
 - 0s - loss: 204.7715 - val_loss: 212.7510
Epoch 36/50
 - 0s - loss: 193.4827 - val_loss: 198.5868
Epoch 37/50
 - 0s - loss: 181.6829 - val_loss: 185.7324
Epoch 38/50
 - 0s - loss: 171.1056 - val_loss: 173.7095
Epoch 39/50
 - 0s - loss: 161.1847 - val_loss: 160.9872
Epoch 40/50
 - 0s - loss: 151.4682 - val_loss: 150.2612
Epoch 41/50
 - 0s - loss: 143.3389 - val_loss: 138.6107
Epoch 42/50
 - 0s - loss: 135.0576 - val_loss: 128.6550
Epoch 43/50
 - 0s - loss: 127.6614 - val_loss: 119.4659
Epoch 44/50
 - 0s - loss: 120.1389 - val_loss: 110.3719
Epoch 45/50
 - 0s - loss: 113.4993 - val_loss: 102.1450
Epoch 46/50
 - 0s - loss: 106.8924 - val_loss: 94.4211
Epoch 47/50
 - 0s - loss: 101.0667 - val_loss: 87.1130
Epoch 48/50
 - 0s - loss: 95.5357 - val_loss: 80.1573
Epoch 49/50
 - 0s - loss: 90.8526 - val_loss: 74.0776
Epoch 50/50
 - 0s - loss: 85.9108 - val_loss: 68.9504